"use client";

import React from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { useT } from "@/lib/i18n/useT";
import { today } from "@/lib/domain/rules";
import { Badge, Button, Card, Skeleton } from "@quikit/ui";
import {
  Printer,
  Download,
  ShieldAlert,
  AlertTriangle,
  Award,
  ArrowLeft,
} from "lucide-react";

export default function GapReportPage() {
  const { t, locale } = useT();
  const asOf = today();

  const { data: report, isLoading, isError } = useQuery({
    queryKey: ["report-gaps", asOf],
    queryFn: async () => {
      const res = await fetch(`/api/reports/gaps?asOf=${asOf}`);
      if (!res.ok) throw new Error("Failed to load gap report");
      const json = await res.json();
      return json.data;
    },
  });

  const handlePrint = () => {
    window.print();
  };

  const handleExportCsv = () => {
    if (!report) return;

    // Build client-side CSV strictly adhering to envelope rules
    const rows = [
      ["Report Type", "SkillsForge Skills Gap & SPOF Report"],
      ["As Of Date", report.asOf],
      ["Generated At", report.generatedAt],
      ["Generated By", report.generatedBy],
      [],
      ["--- SINGLE POINTS OF FAILURE (SPOF MACHINES) ---"],
      ["Machine Code", "Machine Name", "Criticality", "Qualified Count", "Trainer Count", "Risk Score", "Lone Operators"],
      ...report.spofs.map((s: any) => [
        s.skill.code,
        `"${s.skill.name}"`,
        s.skill.criticality,
        s.qualifiedCount,
        s.trainerCount,
        s.risk.score,
        `"${s.loneOperators.map((o: any) => `${o.name} (L${o.level})`).join(", ")}"`,
      ]),
      [],
      ["--- RED SHIFT CELLS (<2 QUALIFIED) ---"],
      ["Machine Code", "Machine Name", "Shift", "Qualified Count", "Trainer Count", "Turns Red On"],
      ...report.redCells.map((c: any) => [
        c.skill.code,
        `"${c.skill.name}"`,
        c.shift.code,
        c.qualifiedCount,
        c.trainerCount,
        c.turnsRedOn || "Immediate",
      ]),
    ];

    const csvContent = "data:text/csv;charset=utf-8," + rows.map((e) => e.join(",")).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `skillsforge_gap_report_${report.asOf}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (isLoading) {
    return (
      <div className="space-y-6 max-w-5xl mx-auto p-4">
        <Skeleton className="h-8 w-64" />
        <Skeleton className="h-40 w-full" />
        <Skeleton className="h-96 w-full" />
      </div>
    );
  }

  if (isError || !report) {
    return (
      <div className="p-8 text-center text-red-600 bg-red-50 rounded-xl">
        Failed to load gap report.
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-12 print:p-0 print:max-w-none">
      {/* Top Bar with Print and Export Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 print:hidden">
        <div>
          <Link
            href="/reports"
            className="text-xs font-semibold text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 inline-flex items-center gap-1 mb-2"
          >
            <ArrowLeft className="w-3.5 h-3.5" /> Back to Reports
          </Link>
          <h1 className="text-2xl font-black tracking-tight text-slate-900 dark:text-slate-100">
            {t("nav.gaps")}
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Operational single points of failure (SPOFs), thin shift cells, and risk ranking
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleExportCsv}>
            <Download className="w-3.5 h-3.5 mr-1.5" />
            {t("common.exportCsv")}
          </Button>

          <Button variant="primary" size="sm" onClick={handlePrint}>
            <Printer className="w-3.5 h-3.5 mr-1.5" />
            {t("common.print")}
          </Button>
        </div>
      </div>

      {/* Printable Report Header */}
      <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 space-y-4 print:border-none print:shadow-none print:p-0">
        <div className="flex items-center justify-between border-b pb-4 dark:border-slate-800">
          <div>
            <h2 className="text-xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
              SKILLSFORGE FACTORY GAP & RESILIENCE AUDIT
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Evaluated strictly under Rule C4: SPOFs &lt;2 qualified operators across shifts
            </p>
          </div>

          <div className="text-right text-xs text-slate-500 font-mono">
            <div>
              <span className="font-semibold">{t("common.asOf")}:</span> {report.asOf}
            </div>
            <div>
              <span className="font-semibold">Generated:</span> {report.generatedAt.split("T")[0]}
            </div>
            <div>
              <span className="font-semibold">Auditor:</span> {report.generatedBy}
            </div>
          </div>
        </div>

        {/* Section 1: Single Points of Failure (SPOFs) */}
        <div className="space-y-3 pt-2">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-bold text-red-700 dark:text-red-400 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5" />
              1. Single Points of Failure ({report.spofs.length} machines with &lt;2 qualified backups)
            </h3>
            <span className="text-xs text-slate-400 font-mono">DB-side GroupBy Aggregation</span>
          </div>

          <div className="w-full overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800">
            <table className="w-full text-left text-sm border-collapse">
              <thead className="bg-slate-50 dark:bg-slate-800/80 text-xs font-semibold text-slate-600 dark:text-slate-300">
                <tr>
                  <th className="p-3">Machine</th>
                  <th className="p-3 text-center">Criticality</th>
                  <th className="p-3 text-center">Total Qualified</th>
                  <th className="p-3">Lone Qualified Operator(s)</th>
                  <th className="p-3 text-center">Trainer</th>
                  <th className="p-3 text-center">Risk Score</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {report.spofs.map((spof: any) => {
                  const displayName =
                    locale === "hi" && spof.skill.nameHi ? spof.skill.nameHi : spof.skill.name;

                  return (
                    <tr key={spof.skill.id} className="hover:bg-red-50/30">
                      <td className="p-3">
                        <span className="font-bold font-mono text-slate-900 dark:text-slate-100 block">
                          {spof.skill.code}
                        </span>
                        <span className="text-xs text-slate-500">{displayName}</span>
                      </td>

                      <td className="p-3 text-center">
                        <Badge variant={spof.skill.criticality === 3 ? "red" : "amber"}>
                          Crit {spof.skill.criticality}
                        </Badge>
                      </td>

                      <td className="p-3 text-center">
                        <span className="font-black font-mono text-base text-red-600">
                          {spof.qualifiedCount}
                        </span>
                      </td>

                      <td className="p-3">
                        {spof.loneOperators.length === 0 ? (
                          <span className="text-xs text-red-600 font-bold">
                            ZERO QUALIFIED (CRITICAL)
                          </span>
                        ) : (
                          spof.loneOperators.map((op: any) => (
                            <div key={op.id} className="text-xs text-slate-800 dark:text-slate-200">
                              <span className="font-semibold">{op.name}</span> (L{op.level})
                              {op.daysToExpiry !== null && (
                                <span className="text-[11px] text-amber-600 ml-1">
                                  [exp: {op.daysToExpiry}d]
                                </span>
                              )}
                            </div>
                          ))
                        )}
                      </td>

                      <td className="p-3 text-center">
                        {spof.trainerCount > 0 ? (
                          <span className="text-xs text-emerald-600 font-semibold inline-flex items-center gap-1">
                            <Award className="w-3.5 h-3.5" /> Yes ({spof.trainerCount})
                          </span>
                        ) : (
                          <span className="text-xs text-red-600 font-semibold">None (0)</span>
                        )}
                      </td>

                      <td className="p-3 text-center">
                        <Badge variant={spof.risk.score >= 70 ? "red" : "amber"}>
                          Risk {spof.risk.score}/100
                        </Badge>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Section 2: Red Shift Cells */}
        <div className="space-y-3 pt-6 border-t dark:border-slate-800">
          <h3 className="text-base font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-amber-600" />
            2. High Risk Shift Cells ({report.redCells.length} shift-machine pairs &lt;2 qualified)
          </h3>

          <div className="w-full overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800">
            <table className="w-full text-left text-sm border-collapse">
              <thead className="bg-slate-50 dark:bg-slate-800/80 text-xs font-semibold text-slate-600 dark:text-slate-300">
                <tr>
                  <th className="p-3">Machine</th>
                  <th className="p-3 text-center">Shift</th>
                  <th className="p-3 text-center">Qualified Count</th>
                  <th className="p-3 text-center">Trainers</th>
                  <th className="p-3">Future Risk / Turn Red Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {report.redCells.map((cell: any) => {
                  const displayName =
                    locale === "hi" && cell.skill.nameHi ? cell.skill.nameHi : cell.skill.name;

                  return (
                    <tr key={`${cell.skill.id}_${cell.shift.id}`}>
                      <td className="p-3">
                        <span className="font-bold font-mono text-slate-900 dark:text-slate-100">
                          {cell.skill.code}
                        </span>{" "}
                        <span className="text-xs text-slate-500">({displayName})</span>
                      </td>

                      <td className="p-3 text-center font-bold text-xs">
                        Shift {cell.shift.code}
                      </td>

                      <td className="p-3 text-center font-mono font-bold text-red-600">
                        {cell.qualifiedCount}
                      </td>

                      <td className="p-3 text-center font-mono text-xs">
                        {cell.trainerCount}
                      </td>

                      <td className="p-3 text-xs text-slate-500">
                        {cell.turnsRedOn ? `Turns red on ${cell.turnsRedOn}` : "Currently under minimum threshold"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Footer Audit Signoff */}
        <div className="pt-8 border-t dark:border-slate-800 text-xs text-slate-500 flex justify-between items-end">
          <div>
            <p className="font-semibold text-slate-700 dark:text-slate-300">
              SkillsForge Quality & Safety Assurance
            </p>
            <p>Report generated for ISO-9001 operator qualification compliance.</p>
          </div>
          <div className="w-48 border-t border-slate-400 text-center pt-1 font-mono text-[11px]">
            Supervisor Signature
          </div>
        </div>
      </div>
    </div>
  );
}
